-------------------------------------------------------------------------------
Test set: com.lotus.uccp.consentmgmt.dao.OrganizationUnitTests
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.361 s <<< FAILURE! - in com.lotus.uccp.consentmgmt.dao.OrganizationUnitTests
saveTest  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.lotus.uccp.auth.repository.UserRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent

getlistTest  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.lotus.uccp.auth.repository.UserRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent

testContext  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.lotus.uccp.auth.repository.UserRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.lotus.uccp.authentication.model.PersonConsentHistory.personConsent references an unknown entity: com.lotus.uccp.authentication.model.PersonConsent

